// Code generated by protoc-gen-go.
// source: user_auth.proto
// DO NOT EDIT!

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserAuthRequest struct {
	GithubId             string `protobuf:"bytes,1,opt,name=github_id,json=githubId" json:"github_id,omitempty"`
	GithubName           string `protobuf:"bytes,2,opt,name=github_name,json=githubName" json:"github_name,omitempty"`
	GithubProfileIconUrl string `protobuf:"bytes,4,opt,name=github_profile_icon_url,json=githubProfileIconUrl" json:"github_profile_icon_url,omitempty"`
}

func (m *UserAuthRequest) Reset()                    { *m = UserAuthRequest{} }
func (m *UserAuthRequest) String() string            { return proto.CompactTextString(m) }
func (*UserAuthRequest) ProtoMessage()               {}
func (*UserAuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *UserAuthRequest) GetGithubId() string {
	if m != nil {
		return m.GithubId
	}
	return ""
}

func (m *UserAuthRequest) GetGithubName() string {
	if m != nil {
		return m.GithubName
	}
	return ""
}

func (m *UserAuthRequest) GetGithubProfileIconUrl() string {
	if m != nil {
		return m.GithubProfileIconUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*UserAuthRequest)(nil), "service.UserAuthRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthUser service

type AuthUserClient interface {
	Auth(ctx context.Context, in *UserAuthRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type authUserClient struct {
	cc *grpc.ClientConn
}

func NewAuthUserClient(cc *grpc.ClientConn) AuthUserClient {
	return &authUserClient{cc}
}

func (c *authUserClient) Auth(ctx context.Context, in *UserAuthRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/service.AuthUser/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthUser service

type AuthUserServer interface {
	Auth(context.Context, *UserAuthRequest) (*UserResponse, error)
}

func RegisterAuthUserServer(s *grpc.Server, srv AuthUserServer) {
	s.RegisterService(&_AuthUser_serviceDesc, srv)
}

func _AuthUser_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.AuthUser/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserServer).Auth(ctx, req.(*UserAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthUser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.AuthUser",
	HandlerType: (*AuthUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _AuthUser_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_auth.proto",
}

func init() { proto.RegisterFile("user_auth.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2d, 0x4e, 0x2d,
	0x8a, 0x4f, 0x2c, 0x2d, 0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0x2d,
	0x2a, 0xcb, 0x4c, 0x4e, 0x95, 0x12, 0x2e, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x8d, 0x07,
	0x29, 0x81, 0xc8, 0x2a, 0xb5, 0x31, 0x72, 0xf1, 0x87, 0x16, 0xa7, 0x16, 0x39, 0x96, 0x96, 0x64,
	0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x73, 0x71, 0xa6, 0x67, 0x96, 0x64, 0x94,
	0x26, 0xc5, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x71, 0x40, 0x04, 0x3c, 0x53,
	0x84, 0xe4, 0xb9, 0xb8, 0xa1, 0x92, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x69, 0x2e, 0x88,
	0x90, 0x5f, 0x62, 0x6e, 0xaa, 0x90, 0x29, 0x97, 0x38, 0x54, 0x41, 0x41, 0x51, 0x7e, 0x5a, 0x66,
	0x4e, 0x6a, 0x7c, 0x66, 0x72, 0x7e, 0x5e, 0x7c, 0x69, 0x51, 0x8e, 0x04, 0x0b, 0x58, 0xb1, 0x08,
	0x44, 0x3a, 0x00, 0x22, 0xeb, 0x99, 0x9c, 0x9f, 0x17, 0x5a, 0x94, 0x63, 0xe4, 0xca, 0xc5, 0x01,
	0x72, 0x03, 0xc8, 0x2d, 0x42, 0x96, 0x5c, 0x2c, 0x20, 0xb6, 0x90, 0x84, 0x1e, 0xd4, 0xed, 0x7a,
	0x68, 0x4e, 0x94, 0x12, 0x45, 0x91, 0x09, 0x82, 0x7a, 0x4c, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x2d,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x09, 0xe8, 0x1f, 0x07, 0x01, 0x00, 0x00,
}
